name: ToolSet
main: com.zndevs.toolset.ToolSet
version: 2.0.0-SNAPSHOT

description: Modularly enhance your Spigot Server

author: "ZNDevelopers (zoweb and NickBland)"
website: zndevs.com

database: false

depend: []
loadbefore: []

commands:
  toolset:
    description: ToolSet Base plugin controller